#!/usr/bin/env python
# encoding: utf-8

import os
import fnmatch


def build(bld):
    # Flags
    cxxflags = bld.get_env()["CXXFLAGS"]

    path = bld.path.abspath() + "/../../rsc"

    # Includes
    includes = ".."

    # Libraries
    libname = bld.env["libname"]
    libs = bld.env["libs"]

    # Get source files
    examples_srcs = []
    for root, dirnames, filenames in os.walk(bld.path.abspath()):
        for filename in fnmatch.filter(filenames, "*.cpp"):
            examples_srcs.append(os.path.join(root, filename))

    examples_srcs = [f[len(bld.path.abspath()) + 1:] for f in examples_srcs]

    for example in examples_srcs:
        bld.program(
            features="cxx",
            install_path=None,
            source=example,
            includes=includes,
            uselib=libs,
            use=libname,
            cxxflags=cxxflags +
            ['-DEXAMPLE_ROBOT_RESOURCE_DIR="' + path + '"'],
            target=example[: len(example) - len(".cpp")],
        )
